### ISSUE TITLE
Installation Issue: miRspongeR_2.8.0.tar.gz Not Available

### ISSUE THREAD

**Issue by raunimarques** [zhangjunpeng411/miRsponge#3]
Hello,

I am encountering an issue while trying to install the miRspongeR package from Bioconductor. The installation fails with a 404 error because the source package miRspongeR_2.8.0.tar.gz is not available at the expected URL.

**Details:
Error Message:**

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://bioconductor.org/packages/3.19/bioc/src/contrib/miRspongeR_2.8.0.tar.gz'
HTTP status was '404 Not Found'

I have tried the following solutions without success:

Checking the URL manually, which returns a 404 error.
Attempting installation via different methods.
Could you please provide guidance on how to resolve this issue or update the package availability?

Thank you for your assistance.

Best regards,
Rauni

**Comment by zhangjunpeng411** [comment]
Hi Rauni,

The issue of miRspongeR has been fixed. Now, you need to download miRspongeR_2.8.1.tar.gz available.

Regards,
Junpeng
