### ISSUE TITLE
Error in if (method == "miRHomology_parallel" | method == "pc_parallel" |  :    the condition has length > 1 O

### ISSUE THREAD

**Issue by raunimarques** [zhangjunpeng411/miRsponge#4]
Hi, 
I'm trying to run the miRspongeR package, but I'm receiving the following error message:

Error in if (method == "miRHomology_parallel" | method == "pc_parallel" |  : 
  the condition has length > 1

I've tried different ways to fix this error, but I'm still getting the message.
What could be causing this error?

**Comment by zhangjunpeng411** [comment]
Hi Rauni,

Please check your input method parameter. The input format can refer to the help document (https://bioconductor.org/packages/devel/bioc/vignettes/miRspongeR/inst/doc/miRspongeR.html#mirhomology). 

I have run the two methods, and they are OK. So I don't know what is your case.

Regards,
Junpeng Zhang

**Comment by raunimarques** [comment]
It worked! Thanks for your help!
