### ISSUE TITLE
List of miRNA names

### ISSUE THREAD

**Issue by raunimarques** [zhangjunpeng411/miRsponge#5]
Hello,
I ran the code to identify the sponges, and I have a data frame containing the sponge names, the number of shared miRNAs, and the p-value. How can I obtain the names of the miRNAs associated with these sponges?

**Comment by zhangjunpeng411** [comment]
Hi,

You can use our miRSM R package (https://bioconductor.org/packages/miRSM/). The function 'share_miRs' will work. Noted that the input variable 'Modulelist' will be a list of your identified ceRNA interactions. For example, if you have identified two ceRNA interactions (A-B, A-C), then Modulelist <- list(c(A, B), c(A ,C)). Moreover, the input variable 'miRTarget' should be a SummarizedExperiment object.

Regards,
Junpeng Zhang
